name: custompiece_hangingplant1.2
piecehammer: Cultivator
m_name: $custompiece_hangingplant1L
sizeMultiplier: 1
m_description: $custompiece_hangingplant1L_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Ð¡ontraband Plants
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort:
  comfort: 2
  comfortGroup: Bed
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 400
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Normal
    m_spirit: Normal
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- Ygg_SmuggledSeeds:2:0:True
- Ygg_Clay:2:0:True
- Ygg_BlackSoil:2:0:True
